modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="shaders"
version="1.1.0"
displayName="Shaders NegativeStudios"
displayURL="https://sites.google.com/view/negativemc/inicio"
credits="NegativeStudios"
authors="NegativeStudios, MrLion303"
description="Post-processing shader effects inspired by Minecraft 1.8 Super Secret Settings."

[[dependencies.shaders]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
